# Javascript Node CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  framer: cli-orb/framer@1.2.0

workflows:
  version: 2.1
  build:
    jobs:
      - framer/build:
          filters:
            branches:
              only: master
