# Javascript Node CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  # framer: cli-orb/framer@1.7.0
  framer: framer/bridge@dev:0.0.1

workflows:
  version: 2.1
  build-project:
    triggers:
      - schedule:
          cron: "30 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - framer/component-import:
          component-library-package: "carbon-components-react"
          dependant-libraries: "carbon-components-react,carbon-components,@carbon/icons-react"
          framer-project-path: "./design-system.framerfx"
          color-token-path: ""
          icon-path: ""

  build-and-publish:
    jobs:
      - framer/build:
          framer-project-path: "./design-system.framerfx"
          filters:
            branches:
              only: master
      - framer/publish:
          framer-project-path: "./design-system.framerfx"
          requires:
            - framer/build
          filters:
            branches:
              only: master
