# Javascript Node CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  framer: cli-orb/framer@1.4.0

workflows:
  version: 2.1
  build-project:
    jobs:
      - framer/say-goodbye:
          who: "Addison"
