# Javascript Node CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  framer: cli-orb/framer@1.3.0

workflows:
  version: 2.1
  build-project:
    # jobs:
    #   - framer/build:
    #       filters:
    #         branches:
    #           only: master
    jobs:
      - framer/build:
          docker:
            - image: circleci/node:10

          working_directory: ~/repo

          steps:
            - checkout
            - run: echo starting parameter job
            - say-hello:
                who: "Addison"
            - run: echo ending parameter job
            - run: echo starting default job
            - say-hello
            - run: echo ending default job
